### ISSUE TITLE
undefined method `click' for nil:NilClass

### ISSUE THREAD

**Issue by frdmn** [lodestone/kindle#6]
I'm stuck with this new error now:

    ➜  ~  kindle
    Enter your Amazon.com username:  jonas.friedmann@***.***
    Enter your Amazon.com password (This is not stored):  ****************
    Getting your kindle highlights...
    undefined method `click' for nil:NilClass
    Crud, something went wrong..

**Comment by kyamaguchi** [comment]
I got the same issue.
This may come from the protection on login.

I signed in with answering security question on browser once. Then it was OK to continue with `kindle` command. 

![amazon_com_login_protection](https://cloud.githubusercontent.com/assets/275284/6142667/d677879e-b1fd-11e4-9f4e-acabd487d87f.png)

The browser I used for security question was Chrome and it doesn't match the user agent which is used in the gem(Windows IE 9). But it was OK.
Amazon.com may check IP Address or something else.

**Comment by tgray** [comment]
I had this issue as well.  Couldn't figure it out.

**Comment by tobiasvl** [comment]
Perhaps rescue the exception and raise a custom exception that's a bit more explanatory? Maybe call it something with "Captcha" in the name and with a message telling you to open your browser and sign in.

**Comment by lodestone** [comment]
Sorry this issue got lost. I'll see what I can do to handle this!

**Comment by lodestone** [comment]
Closing this for now. I've released a major rewrite of the codebase. If this comes up again please open another issue! Cheers!
